DROP TABLE DOCS_DATAGRID_CELL;
CREATE TABLE DOCS_DATAGRID_CELL (
DOCUMENT_ID     VARCHAR(36) NOT NULL,
RECORD_ID       INT NOT NULL,
CELL_ID         INT NOT NULL,
VALUE           TEXT,
CONSTRAINT PRIMARY KEY(DOCUMENT_ID, RECORD_ID, CELL_ID)
);
