CREATE TABLE CONTENT (
    CONTENT_ID      VARCHAR(64),
    CONTENT_TYPE    VARCHAR(255),
    STATUS          INT,
    TITLE           TEXT,
    BODY            TEXT,
    CREATE_DATE     DATETIME,
    UPDATE_DATE     DATETIME,
    OWNER_ID        VARCHAR(64),
    ACL_ID          VARCHAR(64),
    PRIMARY KEY (CONTENT_ID, STATUS)
);
CREATE TABLE CONTENT_HISTORY (
    CONTENT_ID      VARCHAR(64),
    CONTENT_TYPE    VARCHAR(255),
    VERSION         VARCHAR(16),
    TITLE           TEXT,
    BODY            TEXT,
    CREATE_DATE     DATETIME,
    UPDATE_DATE     DATETIME,
    OWNER_ID        VARCHAR(64),
    ACL_ID          VARCHAR(64),
    PRIMARY KEY (CONTENT_ID, VERSION)
);
