DROP TABLE DOCS_CHAT;

CREATE TABLE DOCS_CHAT (
  DOCUMENT_ID VARCHAR(36),
  CHAT_ID     BIGINT,
  USER_ID     VARCHAR(36),
  DATE        DATETIME,
  MESSAGE     TEXT,
  PRIMARY KEY (DOCUMENT_ID, CHAT_ID)
);

SELECT C.DOCUMENT_ID,
       A.DISPLAY_NAME USER_NAME,
       C.DATE,
       C.MESSAGE
FROM   DOCS_CHAT C
LEFT JOIN AUTH_USER A
ON     C.USER_ID = A.USER_ID
;
